WITH RECURSIVE GENERATIONS (ID, GENERATION) AS (
    SELECT ID, 1
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECOLI_DATA.ID, GENERATION + 1
        FROM GENERATIONS
        INNER JOIN ECOLI_DATA
            ON GENERATIONS.ID = ECOLI_DATA.PARENT_ID
        WHERE GENERATION <= 3
)

SELECT ID
    FROM GENERATIONS
    WHERE GENERATION = 3
    ORDER BY ID ASC;
