WITH RECURSIVE GENERATIONS (ID, GENERATION) AS (
    SELECT ID, 1
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECOLI_DATA.ID, GENERATION + 1
        FROM GENERATIONS
        INNER JOIN ECOLI_DATA
            ON GENERATIONS.ID = ECOLI_DATA.PARENT_ID
)

SELECT COUNT(*) AS COUNT,
        GENERATION
    FROM GENERATIONS
    WHERE ID NOT IN (
        SELECT PARENT_ID
            FROM ECOLI_DATA
            WHERE PARENT_ID IS NOT NULL
    )
    GROUP BY GENERATION
    ORDER BY GENERATION ASC;

