WITH YEAR_AND_SIZE AS
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR
)

SELECT YEAR_AND_SIZE.YEAR AS YEAR,
        YEAR_AND_SIZE.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV,
        ECOLI_DATA.ID
    FROM ECOLI_DATA
    INNER JOIN YEAR_AND_SIZE
        ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = YEAR_AND_SIZE.YEAR
    ORDER BY YEAR ASC, YEAR_DEV ASC;

