WITH MAX_FISH AS
(
    SELECT MAX(LENGTH) AS LENGTH,
            FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
)

SELECT FISH_INFO.ID AS ID,
        FISH_NAME_INFO.FISH_NAME AS FISH_NAME,
        MAX_FISH.LENGTH AS LENGTH
    FROM MAX_FISH
    INNER JOIN FISH_NAME_INFO
        ON MAX_FISH.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    INNER JOIN FISH_INFO
        ON MAX_FISH.LENGTH = FISH_INFO.LENGTH
            AND MAX_FISH.FISH_TYPE = FISH_INFO.FISH_TYPE
    ORDER BY ID ASC;