WITH MAX_SCORE AS
(
    SELECT SUM(SCORE) AS `SUM`,
            EMP_NO AS EMP_NO 
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY `SUM` DESC
        LIMIT 1
)

SELECT `SUM` AS SCORE, MAX_SCORE.EMP_NO, EMP_NAME, POSITION, EMAIL
    FROM MAX_SCORE
    INNER JOIN HR_EMPLOYEES
        ON MAX_SCORE.EMP_NO = HR_EMPLOYEES.EMP_NO;

